- _data/sites.json
> Añadidos mas sitios y traducciones al español

- _data/sites.json
> Ebay repetido

- _data/sites.json
- Most data you can get is not available to you directly
- Getting your data requires a captcha (for login), a captcha (for data takeout), 2 e-mail confirmations, and a waiting period of a week.
> Spotify: change to hard and add additional details.

- _data/sites.json
~~hehe oops~~ merged the two reddit entries since I didn't notice the first one.
- Added Duolingo as medium
- Added Fedex as hard
> Remove reddit dupe (+ add Duolingo and Fedex)

- _data/sites.json
Closes #78 (somewhat), I'll get to the workflow later.
> Clean up all of the entries

- _data/sites.json
Adding Kwai and putting Netflix and TikTok as a popular sites.
> Adding Kwai as hard.

- _data/sites.json
> Added UOL.

- _data/sites.json
Here comes our first limited entry
> Add Roblox as limited

- .github/ISSUE_TEMPLATE/new_entry.md
- .github/ISSUE_TEMPLATE/update_entry.md
- TRANSLATION_REFERENCE.md
**updated TRANSLATION_REFERENCE.md**
* added reference to Crowdin
* removed redundant references to the jdm chrome extension (#94)
**updated new_entry.md**
* removed redundant references to the jdm chrome extension (#94)
**updated update_entry.md**
* removed redundant references to the jdm chrome extension (#94)
* added `email_subject`
* added `limited` to new difficulty options
> updated TRANSLATION_REFERENCE.md and .github/ISSUE_TEMPLATE

- _data/sites.json
Add Freelancer.com website
- created notes
- created email-adress
- created url
- validated json
> Add Freelancer

- _data/sites.json
Changed bot mentions (@gdprbot and @lgpdbot) to href for `Telegram`
> changed bot mentions to href for Telegram

- TRANSLATION_REFERENCE.md
- _data/sites.json
replaced emails in `notes` with `<a href=\"\">mailto:</a>` links
> changed emails in notes to mailto links

- _data/sites.json
> removed notes_es-ES and notes_cs-CZ from Yahoo!

- _data/sites.json
> removed notes_es-ES and notes_cs-CZ from YOIGO

- _data/sites.json
I almost wanted to make a separate difficulty level because of how excessive the requirements are.
> Add Student Beans as hard

- _data/sites.json
This is my first PR for this project. I read the contributing guidelines, but just wanted to make sure this was okay by adding another link to the web form in the Notes, and also an email and phone number.
Also, should I limit commits to one new company/entry? Thank you, and I look forward to helping out more!
> Add Chick-fil-A as medium

- _data/sites.json
This pull request solved the problems that @vivelamode11 had with his pull request [#116]
> Solved problems with pull request #116

- _data/sites.json
Doesn't really get **all** of your data (couldn't find a way to do that), but it gets most of the transactions.
> add paypal

- _data/sites.json
> Add GoDaddy as easy

- _data/sites.json
> Add Anthropic as easy

- _data/sites.json
> Update Amazon to easy

- _data/sites.json
> Add Quaidesamours as easy
